/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "AllowedBaseTokens",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AllowedBaseTokens__factory>;
    getContractFactory(
      name: "BonusReserveManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BonusReserveManager__factory>;
    getContractFactory(
      name: "IAllowedBaseTokensLike",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAllowedBaseTokensLike__factory>;
    getContractFactory(
      name: "IStudentTokenRegistryLike",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IStudentTokenRegistryLike__factory>;
    getContractFactory(
      name: "IUniswapV2FactoryLike",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV2FactoryLike__factory>;
    getContractFactory(
      name: "PairLauncher",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PairLauncher__factory>;
    getContractFactory(
      name: "ReceiptToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReceiptToken__factory>;
    getContractFactory(
      name: "IBonusReserveManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBonusReserveManager__factory>;
    getContractFactory(
      name: "IReceiptToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IReceiptToken__factory>;
    getContractFactory(
      name: "ReceiptVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReceiptVault__factory>;
    getContractFactory(
      name: "StudentTokenRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StudentTokenRegistry__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "AllowedBaseTokens",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AllowedBaseTokens>;
    getContractAt(
      name: "BonusReserveManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BonusReserveManager>;
    getContractAt(
      name: "IAllowedBaseTokensLike",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAllowedBaseTokensLike>;
    getContractAt(
      name: "IStudentTokenRegistryLike",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IStudentTokenRegistryLike>;
    getContractAt(
      name: "IUniswapV2FactoryLike",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV2FactoryLike>;
    getContractAt(
      name: "PairLauncher",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PairLauncher>;
    getContractAt(
      name: "ReceiptToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReceiptToken>;
    getContractAt(
      name: "IBonusReserveManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBonusReserveManager>;
    getContractAt(
      name: "IReceiptToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IReceiptToken>;
    getContractAt(
      name: "ReceiptVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReceiptVault>;
    getContractAt(
      name: "StudentTokenRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StudentTokenRegistry>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "AllowedBaseTokens",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AllowedBaseTokens>;
    deployContract(
      name: "BonusReserveManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BonusReserveManager>;
    deployContract(
      name: "IAllowedBaseTokensLike",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAllowedBaseTokensLike>;
    deployContract(
      name: "IStudentTokenRegistryLike",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStudentTokenRegistryLike>;
    deployContract(
      name: "IUniswapV2FactoryLike",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IUniswapV2FactoryLike>;
    deployContract(
      name: "PairLauncher",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PairLauncher>;
    deployContract(
      name: "ReceiptToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReceiptToken>;
    deployContract(
      name: "IBonusReserveManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBonusReserveManager>;
    deployContract(
      name: "IReceiptToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReceiptToken>;
    deployContract(
      name: "ReceiptVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReceiptVault>;
    deployContract(
      name: "StudentTokenRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StudentTokenRegistry>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "AllowedBaseTokens",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AllowedBaseTokens>;
    deployContract(
      name: "BonusReserveManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BonusReserveManager>;
    deployContract(
      name: "IAllowedBaseTokensLike",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAllowedBaseTokensLike>;
    deployContract(
      name: "IStudentTokenRegistryLike",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStudentTokenRegistryLike>;
    deployContract(
      name: "IUniswapV2FactoryLike",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IUniswapV2FactoryLike>;
    deployContract(
      name: "PairLauncher",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PairLauncher>;
    deployContract(
      name: "ReceiptToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReceiptToken>;
    deployContract(
      name: "IBonusReserveManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBonusReserveManager>;
    deployContract(
      name: "IReceiptToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReceiptToken>;
    deployContract(
      name: "ReceiptVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReceiptVault>;
    deployContract(
      name: "StudentTokenRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StudentTokenRegistry>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
