/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBonusReserveManager,
  IBonusReserveManagerInterface,
} from "../../../src/ReceiptVault.sol/IBonusReserveManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "hasReserve",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "payBonus",
    outputs: [
      {
        internalType: "uint256",
        name: "paidAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBonusReserveManager__factory {
  static readonly abi = _abi;
  static createInterface(): IBonusReserveManagerInterface {
    return new Interface(_abi) as IBonusReserveManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBonusReserveManager {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IBonusReserveManager;
  }
}
