/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReceiptToken,
  IReceiptTokenInterface,
} from "../../../src/ReceiptVault.sol/IReceiptToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReceiptToken__factory {
  static readonly abi = _abi;
  static createInterface(): IReceiptTokenInterface {
    return new Interface(_abi) as IReceiptTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReceiptToken {
    return new Contract(address, _abi, runner) as unknown as IReceiptToken;
  }
}
