/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAllowedBaseTokensLike } from "./IAllowedBaseTokensLike";
export type { IStudentTokenRegistryLike } from "./IStudentTokenRegistryLike";
export type { IUniswapV2FactoryLike } from "./IUniswapV2FactoryLike";
export type { PairLauncher } from "./PairLauncher";
