/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace PairLauncher {
  export type PairRecordStruct = {
    token: AddressLike;
    baseToken: AddressLike;
    pair: AddressLike;
    creator: AddressLike;
    createdAt: BigNumberish;
    exists: boolean;
  };

  export type PairRecordStructOutput = [
    token: string,
    baseToken: string,
    pair: string,
    creator: string,
    createdAt: bigint,
    exists: boolean
  ] & {
    token: string;
    baseToken: string;
    pair: string;
    creator: string;
    createdAt: bigint;
    exists: boolean;
  };
}

export interface PairLauncherInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowedBaseTokens"
      | "factory"
      | "getAllPairRecords"
      | "getExistingPair"
      | "getPairKey"
      | "getPairRecord"
      | "launchPair"
      | "owner"
      | "pairExists"
      | "registry"
      | "renounceOwnership"
      | "totalPairs"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred" | "PairCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowedBaseTokens",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllPairRecords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExistingPair",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPairKey",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPairRecord",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "launchPair",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pairExists",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPairs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowedBaseTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllPairRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExistingPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPairKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPairRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "launchPair", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pairExists", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalPairs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PairCreatedEvent {
  export type InputTuple = [
    token: AddressLike,
    baseToken: AddressLike,
    pair: AddressLike,
    creator: AddressLike
  ];
  export type OutputTuple = [
    token: string,
    baseToken: string,
    pair: string,
    creator: string
  ];
  export interface OutputObject {
    token: string;
    baseToken: string;
    pair: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PairLauncher extends BaseContract {
  connect(runner?: ContractRunner | null): PairLauncher;
  waitForDeployment(): Promise<this>;

  interface: PairLauncherInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowedBaseTokens: TypedContractMethod<[], [string], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  getAllPairRecords: TypedContractMethod<
    [],
    [PairLauncher.PairRecordStructOutput[]],
    "view"
  >;

  getExistingPair: TypedContractMethod<
    [token: AddressLike, baseToken: AddressLike],
    [string],
    "view"
  >;

  getPairKey: TypedContractMethod<
    [token: AddressLike, baseToken: AddressLike],
    [string],
    "view"
  >;

  getPairRecord: TypedContractMethod<
    [token: AddressLike, baseToken: AddressLike],
    [PairLauncher.PairRecordStructOutput],
    "view"
  >;

  launchPair: TypedContractMethod<
    [token: AddressLike, baseToken: AddressLike],
    [string],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pairExists: TypedContractMethod<
    [token: AddressLike, baseToken: AddressLike],
    [boolean],
    "view"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalPairs: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowedBaseTokens"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllPairRecords"
  ): TypedContractMethod<[], [PairLauncher.PairRecordStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getExistingPair"
  ): TypedContractMethod<
    [token: AddressLike, baseToken: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPairKey"
  ): TypedContractMethod<
    [token: AddressLike, baseToken: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPairRecord"
  ): TypedContractMethod<
    [token: AddressLike, baseToken: AddressLike],
    [PairLauncher.PairRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "launchPair"
  ): TypedContractMethod<
    [token: AddressLike, baseToken: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pairExists"
  ): TypedContractMethod<
    [token: AddressLike, baseToken: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalPairs"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PairCreated"
  ): TypedContractEvent<
    PairCreatedEvent.InputTuple,
    PairCreatedEvent.OutputTuple,
    PairCreatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PairCreated(address,address,address,address)": TypedContractEvent<
      PairCreatedEvent.InputTuple,
      PairCreatedEvent.OutputTuple,
      PairCreatedEvent.OutputObject
    >;
    PairCreated: TypedContractEvent<
      PairCreatedEvent.InputTuple,
      PairCreatedEvent.OutputTuple,
      PairCreatedEvent.OutputObject
    >;
  };
}
