/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBonusReserveManager } from "./IBonusReserveManager";
export type { IReceiptToken } from "./IReceiptToken";
export type { ReceiptVault } from "./ReceiptVault";
