/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ReceiptVault {
  export type VaultPositionStruct = {
    id: BigNumberish;
    owner: AddressLike;
    lpToken: AddressLike;
    lpAmount: BigNumberish;
    receiptAmount: BigNumberish;
    lockedAt: BigNumberish;
    unlockAt: BigNumberish;
    redeemed: boolean;
    exists: boolean;
  };

  export type VaultPositionStructOutput = [
    id: bigint,
    owner: string,
    lpToken: string,
    lpAmount: bigint,
    receiptAmount: bigint,
    lockedAt: bigint,
    unlockAt: bigint,
    redeemed: boolean,
    exists: boolean
  ] & {
    id: bigint;
    owner: string;
    lpToken: string;
    lpAmount: bigint;
    receiptAmount: bigint;
    lockedAt: bigint;
    unlockAt: bigint;
    redeemed: boolean;
    exists: boolean;
  };
}

export interface ReceiptVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LOCK_PERIOD"
      | "bonusReserveManager"
      | "depositLP"
      | "getPosition"
      | "getUserPositionIds"
      | "getUserPositions"
      | "isRedeemable"
      | "nextPositionId"
      | "owner"
      | "receiptToken"
      | "redeemPosition"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PositionCreated"
      | "PositionRedeemed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LOCK_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bonusReserveManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositLP",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPositionIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPositions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRedeemable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPositionId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receiptToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redeemPosition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "LOCK_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bonusReserveManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositLP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPositionIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRedeemable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextPositionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiptToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionCreatedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    owner: AddressLike,
    lpToken: AddressLike,
    lpAmount: BigNumberish,
    receiptAmount: BigNumberish,
    unlockAt: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    owner: string,
    lpToken: string,
    lpAmount: bigint,
    receiptAmount: bigint,
    unlockAt: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    owner: string;
    lpToken: string;
    lpAmount: bigint;
    receiptAmount: bigint;
    unlockAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionRedeemedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    owner: AddressLike,
    lpToken: AddressLike,
    lpReturned: BigNumberish,
    bonusPaid: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    owner: string,
    lpToken: string,
    lpReturned: bigint,
    bonusPaid: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    owner: string;
    lpToken: string;
    lpReturned: bigint;
    bonusPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReceiptVault extends BaseContract {
  connect(runner?: ContractRunner | null): ReceiptVault;
  waitForDeployment(): Promise<this>;

  interface: ReceiptVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LOCK_PERIOD: TypedContractMethod<[], [bigint], "view">;

  bonusReserveManager: TypedContractMethod<[], [string], "view">;

  depositLP: TypedContractMethod<
    [lpToken: AddressLike, lpAmount: BigNumberish, receiptAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getPosition: TypedContractMethod<
    [positionId: BigNumberish],
    [ReceiptVault.VaultPositionStructOutput],
    "view"
  >;

  getUserPositionIds: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  getUserPositions: TypedContractMethod<
    [user: AddressLike],
    [ReceiptVault.VaultPositionStructOutput[]],
    "view"
  >;

  isRedeemable: TypedContractMethod<
    [positionId: BigNumberish],
    [boolean],
    "view"
  >;

  nextPositionId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  receiptToken: TypedContractMethod<[], [string], "view">;

  redeemPosition: TypedContractMethod<
    [positionId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LOCK_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bonusReserveManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "depositLP"
  ): TypedContractMethod<
    [lpToken: AddressLike, lpAmount: BigNumberish, receiptAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [positionId: BigNumberish],
    [ReceiptVault.VaultPositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPositionIds"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserPositions"
  ): TypedContractMethod<
    [user: AddressLike],
    [ReceiptVault.VaultPositionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRedeemable"
  ): TypedContractMethod<[positionId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextPositionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiptToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "redeemPosition"
  ): TypedContractMethod<[positionId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PositionCreated"
  ): TypedContractEvent<
    PositionCreatedEvent.InputTuple,
    PositionCreatedEvent.OutputTuple,
    PositionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PositionRedeemed"
  ): TypedContractEvent<
    PositionRedeemedEvent.InputTuple,
    PositionRedeemedEvent.OutputTuple,
    PositionRedeemedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PositionCreated(uint256,address,address,uint256,uint256,uint256)": TypedContractEvent<
      PositionCreatedEvent.InputTuple,
      PositionCreatedEvent.OutputTuple,
      PositionCreatedEvent.OutputObject
    >;
    PositionCreated: TypedContractEvent<
      PositionCreatedEvent.InputTuple,
      PositionCreatedEvent.OutputTuple,
      PositionCreatedEvent.OutputObject
    >;

    "PositionRedeemed(uint256,address,address,uint256,uint256)": TypedContractEvent<
      PositionRedeemedEvent.InputTuple,
      PositionRedeemedEvent.OutputTuple,
      PositionRedeemedEvent.OutputObject
    >;
    PositionRedeemed: TypedContractEvent<
      PositionRedeemedEvent.InputTuple,
      PositionRedeemedEvent.OutputTuple,
      PositionRedeemedEvent.OutputObject
    >;
  };
}
