/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AllowedBaseTokensInterface extends Interface {
  getFunction(
    nameOrSignature: "allowed" | "isAllowed" | "owner" | "setAllowed"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BaseTokenUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "allowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAllowed",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "allowed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAllowed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAllowed", data: BytesLike): Result;
}

export namespace BaseTokenUpdatedEvent {
  export type InputTuple = [token: AddressLike, allowed: boolean];
  export type OutputTuple = [token: string, allowed: boolean];
  export interface OutputObject {
    token: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AllowedBaseTokens extends BaseContract {
  connect(runner?: ContractRunner | null): AllowedBaseTokens;
  waitForDeployment(): Promise<this>;

  interface: AllowedBaseTokensInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isAllowed: TypedContractMethod<[token: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setAllowed: TypedContractMethod<
    [token: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAllowed"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAllowed"
  ): TypedContractMethod<
    [token: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BaseTokenUpdated"
  ): TypedContractEvent<
    BaseTokenUpdatedEvent.InputTuple,
    BaseTokenUpdatedEvent.OutputTuple,
    BaseTokenUpdatedEvent.OutputObject
  >;

  filters: {
    "BaseTokenUpdated(address,bool)": TypedContractEvent<
      BaseTokenUpdatedEvent.InputTuple,
      BaseTokenUpdatedEvent.OutputTuple,
      BaseTokenUpdatedEvent.OutputObject
    >;
    BaseTokenUpdated: TypedContractEvent<
      BaseTokenUpdatedEvent.InputTuple,
      BaseTokenUpdatedEvent.OutputTuple,
      BaseTokenUpdatedEvent.OutputObject
    >;
  };
}
