/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BonusReserveManager {
  export type BonusReserveStruct = {
    token: AddressLike;
    totalReserved: BigNumberish;
    totalPaid: BigNumberish;
    exists: boolean;
  };

  export type BonusReserveStructOutput = [
    token: string,
    totalReserved: bigint,
    totalPaid: bigint,
    exists: boolean
  ] & {
    token: string;
    totalReserved: bigint;
    totalPaid: bigint;
    exists: boolean;
  };
}

export interface BonusReserveManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllReserves"
      | "getRemainingReserve"
      | "getReserve"
      | "hasReserve"
      | "increaseReserve"
      | "owner"
      | "payBonus"
      | "renounceOwnership"
      | "setReserve"
      | "totalReserveTokens"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BonusPaid"
      | "BonusReserveIncreased"
      | "BonusReserveSet"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAllReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingReserve",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserve",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReserve",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseReserve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payBonus",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setReserve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalReserveTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getReserve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasReserve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "increaseReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payBonus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setReserve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalReserveTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BonusPaidEvent {
  export type InputTuple = [
    token: AddressLike,
    amountPaid: BigNumberish,
    newTotalPaid: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    amountPaid: bigint,
    newTotalPaid: bigint
  ];
  export interface OutputObject {
    token: string;
    amountPaid: bigint;
    newTotalPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BonusReserveIncreasedEvent {
  export type InputTuple = [
    token: AddressLike,
    amountAdded: BigNumberish,
    newTotalReserved: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    amountAdded: bigint,
    newTotalReserved: bigint
  ];
  export interface OutputObject {
    token: string;
    amountAdded: bigint;
    newTotalReserved: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BonusReserveSetEvent {
  export type InputTuple = [token: AddressLike, totalReserved: BigNumberish];
  export type OutputTuple = [token: string, totalReserved: bigint];
  export interface OutputObject {
    token: string;
    totalReserved: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BonusReserveManager extends BaseContract {
  connect(runner?: ContractRunner | null): BonusReserveManager;
  waitForDeployment(): Promise<this>;

  interface: BonusReserveManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllReserves: TypedContractMethod<
    [],
    [BonusReserveManager.BonusReserveStructOutput[]],
    "view"
  >;

  getRemainingReserve: TypedContractMethod<
    [token: AddressLike],
    [bigint],
    "view"
  >;

  getReserve: TypedContractMethod<
    [token: AddressLike],
    [BonusReserveManager.BonusReserveStructOutput],
    "view"
  >;

  hasReserve: TypedContractMethod<[token: AddressLike], [boolean], "view">;

  increaseReserve: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payBonus: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setReserve: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalReserveTokens: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllReserves"
  ): TypedContractMethod<
    [],
    [BonusReserveManager.BonusReserveStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRemainingReserve"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReserve"
  ): TypedContractMethod<
    [token: AddressLike],
    [BonusReserveManager.BonusReserveStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasReserve"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "increaseReserve"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payBonus"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReserve"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalReserveTokens"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BonusPaid"
  ): TypedContractEvent<
    BonusPaidEvent.InputTuple,
    BonusPaidEvent.OutputTuple,
    BonusPaidEvent.OutputObject
  >;
  getEvent(
    key: "BonusReserveIncreased"
  ): TypedContractEvent<
    BonusReserveIncreasedEvent.InputTuple,
    BonusReserveIncreasedEvent.OutputTuple,
    BonusReserveIncreasedEvent.OutputObject
  >;
  getEvent(
    key: "BonusReserveSet"
  ): TypedContractEvent<
    BonusReserveSetEvent.InputTuple,
    BonusReserveSetEvent.OutputTuple,
    BonusReserveSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BonusPaid(address,uint256,uint256)": TypedContractEvent<
      BonusPaidEvent.InputTuple,
      BonusPaidEvent.OutputTuple,
      BonusPaidEvent.OutputObject
    >;
    BonusPaid: TypedContractEvent<
      BonusPaidEvent.InputTuple,
      BonusPaidEvent.OutputTuple,
      BonusPaidEvent.OutputObject
    >;

    "BonusReserveIncreased(address,uint256,uint256)": TypedContractEvent<
      BonusReserveIncreasedEvent.InputTuple,
      BonusReserveIncreasedEvent.OutputTuple,
      BonusReserveIncreasedEvent.OutputObject
    >;
    BonusReserveIncreased: TypedContractEvent<
      BonusReserveIncreasedEvent.InputTuple,
      BonusReserveIncreasedEvent.OutputTuple,
      BonusReserveIncreasedEvent.OutputObject
    >;

    "BonusReserveSet(address,uint256)": TypedContractEvent<
      BonusReserveSetEvent.InputTuple,
      BonusReserveSetEvent.OutputTuple,
      BonusReserveSetEvent.OutputObject
    >;
    BonusReserveSet: TypedContractEvent<
      BonusReserveSetEvent.InputTuple,
      BonusReserveSetEvent.OutputTuple,
      BonusReserveSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
