/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as pairLauncherSol from "./PairLauncher.sol";
export type { pairLauncherSol };
import type * as receiptVaultSol from "./ReceiptVault.sol";
export type { receiptVaultSol };
export type { AllowedBaseTokens } from "./AllowedBaseTokens";
export type { BonusReserveManager } from "./BonusReserveManager";
export type { ReceiptToken } from "./ReceiptToken";
export type { StudentTokenRegistry } from "./StudentTokenRegistry";
