/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace StudentTokenRegistry {
  export type TokenRecordStruct = {
    token: AddressLike;
    creator: AddressLike;
    title: string;
    symbol: string;
    description: string;
    category: string;
    logoUrl: string;
    baseToken: AddressLike;
    bonusEnabled: boolean;
    rewardAsset: AddressLike;
    bonusReserve: BigNumberish;
    createdAt: BigNumberish;
    status: BigNumberish;
    exists: boolean;
  };

  export type TokenRecordStructOutput = [
    token: string,
    creator: string,
    title: string,
    symbol: string,
    description: string,
    category: string,
    logoUrl: string,
    baseToken: string,
    bonusEnabled: boolean,
    rewardAsset: string,
    bonusReserve: bigint,
    createdAt: bigint,
    status: bigint,
    exists: boolean
  ] & {
    token: string;
    creator: string;
    title: string;
    symbol: string;
    description: string;
    category: string;
    logoUrl: string;
    baseToken: string;
    bonusEnabled: boolean;
    rewardAsset: string;
    bonusReserve: bigint;
    createdAt: bigint;
    status: bigint;
    exists: boolean;
  };
}

export interface StudentTokenRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllTokens"
      | "getToken"
      | "getTokenAddresses"
      | "isRegistered"
      | "owner"
      | "registerToken"
      | "renounceOwnership"
      | "totalTokens"
      | "transferOwnership"
      | "updateBonusReserve"
      | "updateDescription"
      | "updateLogo"
      | "updateStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BonusReserveUpdated"
      | "DescriptionUpdated"
      | "LogoUpdated"
      | "OwnershipTransferred"
      | "TokenRegistered"
      | "TokenStatusUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAllTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerToken",
    values: [
      AddressLike,
      string,
      string,
      string,
      string,
      string,
      AddressLike,
      boolean,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBonusReserve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDescription",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLogo",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStatus",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBonusReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateLogo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateStatus",
    data: BytesLike
  ): Result;
}

export namespace BonusReserveUpdatedEvent {
  export type InputTuple = [token: AddressLike, newBonusReserve: BigNumberish];
  export type OutputTuple = [token: string, newBonusReserve: bigint];
  export interface OutputObject {
    token: string;
    newBonusReserve: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DescriptionUpdatedEvent {
  export type InputTuple = [token: AddressLike, newDescription: string];
  export type OutputTuple = [token: string, newDescription: string];
  export interface OutputObject {
    token: string;
    newDescription: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LogoUpdatedEvent {
  export type InputTuple = [token: AddressLike, newLogoUrl: string];
  export type OutputTuple = [token: string, newLogoUrl: string];
  export interface OutputObject {
    token: string;
    newLogoUrl: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenRegisteredEvent {
  export type InputTuple = [
    token: AddressLike,
    creator: AddressLike,
    title: string,
    symbol: string,
    baseToken: AddressLike,
    bonusEnabled: boolean,
    rewardAsset: AddressLike,
    bonusReserve: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    creator: string,
    title: string,
    symbol: string,
    baseToken: string,
    bonusEnabled: boolean,
    rewardAsset: string,
    bonusReserve: bigint
  ];
  export interface OutputObject {
    token: string;
    creator: string;
    title: string;
    symbol: string;
    baseToken: string;
    bonusEnabled: boolean;
    rewardAsset: string;
    bonusReserve: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenStatusUpdatedEvent {
  export type InputTuple = [token: AddressLike, newStatus: BigNumberish];
  export type OutputTuple = [token: string, newStatus: bigint];
  export interface OutputObject {
    token: string;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StudentTokenRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): StudentTokenRegistry;
  waitForDeployment(): Promise<this>;

  interface: StudentTokenRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllTokens: TypedContractMethod<
    [],
    [StudentTokenRegistry.TokenRecordStructOutput[]],
    "view"
  >;

  getToken: TypedContractMethod<
    [token: AddressLike],
    [StudentTokenRegistry.TokenRecordStructOutput],
    "view"
  >;

  getTokenAddresses: TypedContractMethod<[], [string[]], "view">;

  isRegistered: TypedContractMethod<[token: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerToken: TypedContractMethod<
    [
      token: AddressLike,
      title: string,
      symbol: string,
      description: string,
      category: string,
      logoUrl: string,
      baseToken: AddressLike,
      bonusEnabled: boolean,
      rewardAsset: AddressLike,
      bonusReserve: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalTokens: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateBonusReserve: TypedContractMethod<
    [token: AddressLike, newBonusReserve: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateDescription: TypedContractMethod<
    [token: AddressLike, newDescription: string],
    [void],
    "nonpayable"
  >;

  updateLogo: TypedContractMethod<
    [token: AddressLike, newLogoUrl: string],
    [void],
    "nonpayable"
  >;

  updateStatus: TypedContractMethod<
    [token: AddressLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllTokens"
  ): TypedContractMethod<
    [],
    [StudentTokenRegistry.TokenRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getToken"
  ): TypedContractMethod<
    [token: AddressLike],
    [StudentTokenRegistry.TokenRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenAddresses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerToken"
  ): TypedContractMethod<
    [
      token: AddressLike,
      title: string,
      symbol: string,
      description: string,
      category: string,
      logoUrl: string,
      baseToken: AddressLike,
      bonusEnabled: boolean,
      rewardAsset: AddressLike,
      bonusReserve: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalTokens"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateBonusReserve"
  ): TypedContractMethod<
    [token: AddressLike, newBonusReserve: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateDescription"
  ): TypedContractMethod<
    [token: AddressLike, newDescription: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateLogo"
  ): TypedContractMethod<
    [token: AddressLike, newLogoUrl: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateStatus"
  ): TypedContractMethod<
    [token: AddressLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BonusReserveUpdated"
  ): TypedContractEvent<
    BonusReserveUpdatedEvent.InputTuple,
    BonusReserveUpdatedEvent.OutputTuple,
    BonusReserveUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DescriptionUpdated"
  ): TypedContractEvent<
    DescriptionUpdatedEvent.InputTuple,
    DescriptionUpdatedEvent.OutputTuple,
    DescriptionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LogoUpdated"
  ): TypedContractEvent<
    LogoUpdatedEvent.InputTuple,
    LogoUpdatedEvent.OutputTuple,
    LogoUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenRegistered"
  ): TypedContractEvent<
    TokenRegisteredEvent.InputTuple,
    TokenRegisteredEvent.OutputTuple,
    TokenRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "TokenStatusUpdated"
  ): TypedContractEvent<
    TokenStatusUpdatedEvent.InputTuple,
    TokenStatusUpdatedEvent.OutputTuple,
    TokenStatusUpdatedEvent.OutputObject
  >;

  filters: {
    "BonusReserveUpdated(address,uint256)": TypedContractEvent<
      BonusReserveUpdatedEvent.InputTuple,
      BonusReserveUpdatedEvent.OutputTuple,
      BonusReserveUpdatedEvent.OutputObject
    >;
    BonusReserveUpdated: TypedContractEvent<
      BonusReserveUpdatedEvent.InputTuple,
      BonusReserveUpdatedEvent.OutputTuple,
      BonusReserveUpdatedEvent.OutputObject
    >;

    "DescriptionUpdated(address,string)": TypedContractEvent<
      DescriptionUpdatedEvent.InputTuple,
      DescriptionUpdatedEvent.OutputTuple,
      DescriptionUpdatedEvent.OutputObject
    >;
    DescriptionUpdated: TypedContractEvent<
      DescriptionUpdatedEvent.InputTuple,
      DescriptionUpdatedEvent.OutputTuple,
      DescriptionUpdatedEvent.OutputObject
    >;

    "LogoUpdated(address,string)": TypedContractEvent<
      LogoUpdatedEvent.InputTuple,
      LogoUpdatedEvent.OutputTuple,
      LogoUpdatedEvent.OutputObject
    >;
    LogoUpdated: TypedContractEvent<
      LogoUpdatedEvent.InputTuple,
      LogoUpdatedEvent.OutputTuple,
      LogoUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenRegistered(address,address,string,string,address,bool,address,uint256)": TypedContractEvent<
      TokenRegisteredEvent.InputTuple,
      TokenRegisteredEvent.OutputTuple,
      TokenRegisteredEvent.OutputObject
    >;
    TokenRegistered: TypedContractEvent<
      TokenRegisteredEvent.InputTuple,
      TokenRegisteredEvent.OutputTuple,
      TokenRegisteredEvent.OutputObject
    >;

    "TokenStatusUpdated(address,uint8)": TypedContractEvent<
      TokenStatusUpdatedEvent.InputTuple,
      TokenStatusUpdatedEvent.OutputTuple,
      TokenStatusUpdatedEvent.OutputObject
    >;
    TokenStatusUpdated: TypedContractEvent<
      TokenStatusUpdatedEvent.InputTuple,
      TokenStatusUpdatedEvent.OutputTuple,
      TokenStatusUpdatedEvent.OutputObject
    >;
  };
}
