/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStudentTokenRegistryLike,
  IStudentTokenRegistryLikeInterface,
} from "../../../src/PairLauncher.sol/IStudentTokenRegistryLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "isRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IStudentTokenRegistryLike__factory {
  static readonly abi = _abi;
  static createInterface(): IStudentTokenRegistryLikeInterface {
    return new Interface(_abi) as IStudentTokenRegistryLikeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IStudentTokenRegistryLike {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IStudentTokenRegistryLike;
  }
}
