/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUniswapV2FactoryLike,
  IUniswapV2FactoryLikeInterface,
} from "../../../src/PairLauncher.sol/IUniswapV2FactoryLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
    ],
    name: "createPair",
    outputs: [
      {
        internalType: "address",
        name: "pair",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
    ],
    name: "getPair",
    outputs: [
      {
        internalType: "address",
        name: "pair",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IUniswapV2FactoryLike__factory {
  static readonly abi = _abi;
  static createInterface(): IUniswapV2FactoryLikeInterface {
    return new Interface(_abi) as IUniswapV2FactoryLikeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IUniswapV2FactoryLike {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IUniswapV2FactoryLike;
  }
}
